volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: backend/.env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    build: ./backend/
    env_file: backend/.env
  frontend:
    build: ./frontend/
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
  gateway:
    build: ./nginx/
    ports:
      - 9000:80
    volumes:
      - static:/static
